export const COMBAT_CONFIG = {
    PLAYER_MAX_HP: 160,
    ENEMY_MAX_HP: 60,

    DAMAGE_PLAYER: 20,
    DAMAGE_ENEMY: 12,

    KING_MAX_HP: 160,
    KING_DAMAGE: 18,
    KING_SPEED: 105,

    ATTACK_RANGE_X: 55,
    ATTACK_RANGE_Y: 40,
    ATTACK_WINDUP: 0.12,
    ATTACK_ACTIVE: 0.12,

    IFRAME_TIME: 0.25,
    ENEMY_ATK_COOLDOWN: 0.8,

    ENEMY_SPEED: 90,
    ENEMY_STOP_DIST: 45,
} as const;
